safe: true
auto: true
lsi: false
pygments: true
markdown: rdiscount
permalink: /:title.html
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - README.md
author:
  name: mose
  email: mose@mose.com
  github: mose
  twitter: mo5e
title: Mose
baseline: what about it ?
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  compress:
    js: uglifier
    css: sass
  cachebust: hard
  cache_assets: false
  gzip: [ text/css, application/javascript ]

