safe: false
lsi: false
pygments: true
markdown: rdiscount
markdown_ext:  markdown,mkd,mkdn,md
permalink: /:title.html
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - README.md
  - Procfile
  - config.rb
  - MIT-LICENSE.txt
author:
  name: mose
  email: mose@mose.com
  github: mose
  twitter: mo5e
title: Mose
baseline: what about it ?
